"""Build the compliance report (Markdown) and a branded PDF (HTML -> headless Chrome).

The PDF is a professional, print-friendly board document (light theme, AiOpsOne
lime accent) — not a dark social card. Boards print these.
"""
import html
import os
import re
import shutil
import subprocess
import tempfile
from collections import OrderedDict

from .mapping import FAIL, PASS, MANUAL, NOT_ASSESSED, summarise

ICON = {FAIL: "❌", PASS: "✅", MANUAL: "📋", NOT_ASSESSED: "⚠️"}
LABEL = {FAIL: "Not compliant", PASS: "Compliant", MANUAL: "Manual", NOT_ASSESSED: "Not assessed"}


# ---------------------------------------------------------------- Markdown ----
def build_markdown(framework, control_results, ctx, narrate):
    s = summarise(control_results)
    L = []
    L.append(f"# {framework.name} — AWS Compliance Report")
    L.append("")
    L.append(f"**Account:** {ctx.get('account') or 'n/a'}  ·  "
             f"**Region:** {ctx.get('region') or 'n/a'}  ·  "
             f"**Assessed:** {ctx.get('date') or 'n/a'}  ·  "
             f"**Engine:** {ctx.get('engine', 'template')}")
    L.append("")
    L.append("## Executive summary")
    L.append("")
    L.append(f"This report assesses the account against **{framework.name}**"
             f"{(' v' + framework.version) if framework.version else ''}. "
             f"Of **{s['automated']} automated controls**, **{s['pass']} passed** and "
             f"**{s['fail']} failed** — an automated compliance score of **{s['score']}%**. "
             f"A further **{s['manual']} controls require manual assessment** "
             f"(governance/process obligations not observable from AWS APIs)"
             + (f", and **{s['not_assessed']} were not assessed** (no matching findings supplied)." if s['not_assessed'] else "."))
    L.append("")
    if s["fails"]:
        L.append("**Priority controls not met:**")
        for r in s["fails"]:
            L.append(f"- ¶{r.control.paragraph} — {r.control.name} ({len(r.fails)} finding(s))")
        L.append("")

    # group by section, preserving order
    sections = OrderedDict()
    for r in control_results.values():
        sections.setdefault(r.control.section or "Other", []).append(r)

    L.append("## Control-by-control assessment")
    for section, rows in sections.items():
        L.append("")
        L.append(f"### {section}")
        for r in rows:
            c = r.control
            L.append("")
            L.append(f"#### {ICON.get(r.status,'•')} ¶{c.paragraph} — {c.name}  · {LABEL.get(r.status, r.status)}")
            L.append("")
            L.append(narrate(r))
            if r.fails:
                L.append("")
                L.append("> **Evidence:**")
                for f in r.fails[:8]:
                    L.append(f"> - {f['detail']}" + (f"  `{f['resource']}`" if f['resource'] else ""))
                if len(r.fails) > 8:
                    L.append(f"> - …and {len(r.fails) - 8} more")
            if c.reference:
                L.append("")
                L.append(f"_Reference: {c.reference}_")

    if s["fails"]:
        L.append("")
        L.append("## Remediation roadmap")
        for i, r in enumerate(s["fails"], 1):
            L.append(f"{i}. **¶{r.control.paragraph} {r.control.name}** — {r.control.remediation}")

    L.append("")
    L.append("---")
    L.append("_Generated by AiOpsOne Assure. Automated controls reflect Prowler / AWS Config "
             "findings; manual controls require human assessment. Verify against the official "
             "APRA standard. Not legal advice._")
    return "\n".join(L)


# -------------------------------------------------------------------- HTML ----
_BOLD = re.compile(r"\*\*(.+?)\*\*")


def _inline(text):
    """Escape HTML then apply minimal markdown inline (**bold** only).

    We intentionally do NOT convert single-* to italic: framework text contains
    literal IAM wildcards like ``*:*`` / ``s3:*`` that must render verbatim.
    """
    out = html.escape(text or "")
    out = _BOLD.sub(r"<strong>\1</strong>", out)
    return out


_CSS = """
@page { size: A4; margin: 16mm 14mm 18mm 14mm; }
* { box-sizing: border-box; }
body { font-family: -apple-system,'Segoe UI',Inter,Arial,sans-serif; color:#1f2328; font-size:11pt; line-height:1.5; margin:0; }
.bar { height:8px; background:#A3E635; }
.head { padding:18px 0 10px; border-bottom:2px solid #ECECEC; margin-bottom:18px; }
.brand { font-size:10pt; letter-spacing:.22em; text-transform:uppercase; color:#5a7d10; font-weight:800; }
h1 { font-size:21pt; margin:6px 0 4px; letter-spacing:-.3px; }
.meta { color:#6b7280; font-size:9.5pt; }
.score { float:right; text-align:center; border:2px solid #A3E635; border-radius:12px; padding:8px 16px; margin-top:-58px; }
.score b { display:block; font-size:24pt; line-height:1; color:#365314; }
.score span { font-size:8pt; color:#6b7280; text-transform:uppercase; letter-spacing:.1em; }
h2 { font-size:14pt; margin:22px 0 8px; padding-bottom:5px; border-bottom:2px solid #A3E635; }
h3 { font-size:12pt; margin:18px 0 6px; color:#365314; }
.summary { background:#FAFAF5; border:1px solid #EAEADF; border-radius:10px; padding:14px 16px; }
.counts { display:flex; gap:10px; margin:12px 0 0; flex-wrap:wrap; }
.pill { font-size:9pt; font-weight:700; padding:5px 12px; border-radius:20px; border:1px solid #e2e2e2; }
.p-fail{ background:#FEF2F2; color:#b91c1c; border-color:#fecaca; }
.p-pass{ background:#F0FDF4; color:#15803d; border-color:#bbf7d0; }
.p-man { background:#F3F4F6; color:#4b5563; border-color:#e5e7eb; }
.p-na  { background:#FFFBEB; color:#b45309; border-color:#fde68a; }
.ctrl { border:1px solid #ECECEC; border-left:4px solid #cbd5e1; border-radius:8px; padding:12px 14px; margin:10px 0; break-inside:avoid; }
.ctrl.s-FAIL{ border-left-color:#ef4444; } .ctrl.s-PASS{ border-left-color:#22c55e; }
.ctrl.s-MANUAL{ border-left-color:#9ca3af; } .ctrl.s-NOT_ASSESSED{ border-left-color:#f59e0b; }
.ctrl .ttl { font-weight:700; font-size:10.5pt; }
.chip { float:right; font-size:8pt; font-weight:800; padding:3px 9px; border-radius:14px; text-transform:uppercase; letter-spacing:.04em; }
.c-FAIL{ background:#FEF2F2; color:#b91c1c; } .c-PASS{ background:#F0FDF4; color:#15803d; }
.c-MANUAL{ background:#F3F4F6; color:#4b5563; } .c-NOT_ASSESSED{ background:#FFFBEB; color:#b45309; }
.narr { margin:7px 0 0; }
.evid { margin:8px 0 0; padding:8px 10px; background:#FBFBFB; border:1px solid #F0F0F0; border-radius:6px; font-size:8.5pt; color:#475569; }
.evid code { font-family:'SF Mono',Menlo,Consolas,monospace; color:#64748b; }
.ref { font-size:8pt; color:#94a3b8; margin-top:6px; }
ol.road { padding-left:18px; } ol.road li { margin:6px 0; break-inside:avoid; }
.foot { margin-top:22px; padding-top:10px; border-top:1px solid #ECECEC; color:#9ca3af; font-size:8pt; }
"""


def build_html(framework, control_results, ctx, narrate):
    s = summarise(control_results)
    P = []
    P.append("<!DOCTYPE html><html><head><meta charset='utf-8'><style>" + _CSS + "</style></head><body>")
    P.append("<div class='bar'></div>")
    P.append("<div class='head'>")
    P.append("<div class='brand'>AiOpsOne · Assure</div>")
    P.append(f"<h1>{_inline(framework.name)}</h1>")
    P.append(f"<div class='meta'>Account <b>{_inline(ctx.get('account') or 'n/a')}</b> · "
             f"Region {_inline(ctx.get('region') or 'n/a')} · Assessed {_inline(ctx.get('date') or 'n/a')} · "
             f"Engine {_inline(ctx.get('engine', 'template'))}</div>")
    P.append(f"<div class='score'><b>{s['score']}%</b><span>automated</span></div>")
    P.append("</div>")

    # Executive summary
    P.append("<h2>Executive summary</h2><div class='summary'>")
    na = (f" {s['not_assessed']} were not assessed." if s['not_assessed'] else "")
    P.append(f"<div>Assessed against <strong>{_inline(framework.name)}"
             f"{(' v' + framework.version) if framework.version else ''}</strong>. "
             f"Of <strong>{s['automated']} automated controls</strong>, "
             f"<strong>{s['pass']} passed</strong> and <strong>{s['fail']} failed</strong>. "
             f"A further <strong>{s['manual']} require manual assessment</strong>.{na}</div>")
    P.append("<div class='counts'>")
    P.append(f"<span class='pill p-fail'>{s['fail']} failed</span>")
    P.append(f"<span class='pill p-pass'>{s['pass']} passed</span>")
    P.append(f"<span class='pill p-man'>{s['manual']} manual</span>")
    if s['not_assessed']:
        P.append(f"<span class='pill p-na'>{s['not_assessed']} not assessed</span>")
    P.append("</div></div>")

    # group by section
    sections = OrderedDict()
    for r in control_results.values():
        sections.setdefault(r.control.section or "Other", []).append(r)

    P.append("<h2>Control-by-control assessment</h2>")
    for section, rows in sections.items():
        P.append(f"<h3>{_inline(section)}</h3>")
        for r in rows:
            c = r.control
            P.append(f"<div class='ctrl s-{r.status}'>")
            P.append(f"<span class='chip c-{r.status}'>{LABEL.get(r.status, r.status)}</span>")
            P.append(f"<div class='ttl'>¶{_inline(c.paragraph)} — {_inline(c.name)}</div>")
            P.append(f"<div class='narr'>{_inline(narrate(r))}</div>")
            if r.fails:
                P.append("<div class='evid'><b>Evidence</b><br>")
                for f in r.fails[:8]:
                    res = f" <code>{_inline(f['resource'])}</code>" if f['resource'] else ""
                    P.append(f"• {_inline(f['detail'])}{res}<br>")
                if len(r.fails) > 8:
                    P.append(f"…and {len(r.fails) - 8} more<br>")
                P.append("</div>")
            if c.reference:
                P.append(f"<div class='ref'>Reference: {_inline(c.reference)}</div>")
            P.append("</div>")

    if s["fails"]:
        P.append("<h2>Remediation roadmap</h2><ol class='road'>")
        for r in s["fails"]:
            P.append(f"<li><strong>¶{_inline(r.control.paragraph)} {_inline(r.control.name)}</strong> — "
                     f"{_inline(r.control.remediation)}</li>")
        P.append("</ol>")

    P.append("<div class='foot'>Generated by AiOpsOne Assure · automated controls reflect "
             "Prowler / AWS Config findings; manual controls require human assessment. "
             "Verify against the official APRA standard. Not legal advice. · aiopsone.com</div>")
    P.append("</body></html>")
    return "".join(P)


# --------------------------------------------------------------------- PDF ----
def find_chrome():
    env = os.environ.get("ASSURE_CHROME")
    if env and os.path.exists(env):
        return env
    candidates = [
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/Applications/Chromium.app/Contents/MacOS/Chromium",
        "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
    ]
    for name in ("google-chrome", "google-chrome-stable", "chromium", "chromium-browser", "microsoft-edge"):
        p = shutil.which(name)
        if p:
            candidates.insert(0, p)
    return next((c for c in candidates if os.path.exists(c)), None)


class PDFError(RuntimeError):
    pass


def render_pdf(html_str, out_path):
    chrome = find_chrome()
    if not chrome:
        raise PDFError(
            "no Chrome/Chromium found for PDF rendering. Install Chrome, set $ASSURE_CHROME "
            "to its path, or use --format md."
        )
    with tempfile.TemporaryDirectory() as td:
        html_path = os.path.join(td, "report.html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_str)
        cmd = [
            chrome, "--headless=new", "--disable-gpu", "--no-pdf-header-footer",
            f"--print-to-pdf={out_path}", f"file://{html_path}",
        ]
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        if not os.path.exists(out_path) or os.path.getsize(out_path) == 0:
            raise PDFError(f"Chrome failed to produce a PDF: {proc.stderr[-400:] or proc.stdout[-400:]}")
    return out_path
